### ISSUE TITLE
Crashy start

### ISSUE THREAD

**Issue by troyswanson** [RollingWithAdvantage/rwa#3]
```
MHVA74DRVG:rwa troy4461$ npm start

> rwa@0.0.1 start /Users/troy4461/Projects/personal/rwa
> nodemon index.js

4 Jun 14:20:11 - [nodemon] v1.3.8
4 Jun 14:20:11 - [nodemon] to restart at any time, enter `rs`
4 Jun 14:20:11 - [nodemon] watching: *.*
4 Jun 14:20:11 - [nodemon] starting `node index.js`
Running on 127.0.0.1:5000

/Users/troy4461/Projects/personal/rwa/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: getaddrinfo ENOTFOUND undefined undefined:27017
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
4 Jun 14:20:41 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by troyswanson** [comment]
Pretty sure Nodemon isn't loading up the `.env` file.

**Comment by troyswanson** [comment]
Foreman is the thing! Use that instead.
